### ISSUE TITLE
QHY Camera captures asynchronously

### ISSUE THREAD

**Issue by je-lamiaud** [je-lamiaud/phd2#1]
Whatever the time spent guiding the mount, the exposure ends 1000 ms (exposure time) after the previous exposure, not 1000 ms after the end of the mount correction move.

**Comment by je-lamiaud** [comment]
Fixed with commit [c9dbc12306c89eede623f3b7f864cc98ab77ca4d]

**Comment by jiangzhuti** [comment]
Hi,  interested in your change and would like to know to what extent this can improve guiding stability

**Comment by je-lamiaud** [comment]
It depends on your exposure time, and, mainly, the quality of your mount.

If your mount needs only very small corrections, the non synchronicity will not cause a noticeable harm, unless you use guide exposures of several seconds.

In my case, I was using 1 second exposures, with a mount which could drift a couple arc-seconds per second.
The non synchronicity of the exposure makes the guide image dating from before or during the previous guide move, leading to a wrong correction. In my case it was causing overshoots, and oscillation (the opposite of stability 🙂).
With the exposure rendered synchronous, the RMS error was divided by two.
The fix is very simple, you can have a look at the commit.

As the mount also has a slow guide speed (20% diurnal rate), it needs long guide pulses. I therefore implemented another change to make the RA and Dec guide moves simultaneous (issue #2). This reduced the exposure / guide period, and improved again the RMS error.
Although my mount is so so (but lightweight), I can now take long exposures with my Borg at 500 mm focal length.
